# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# 每日早9点到晚8点每2小时运行一次

name: 中青自动阅读2

on:
  workflow_dispatch:
  schedule:
     - cron: '6 1-12/2 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ: ${{ secrets.YOUTH_READ6 }}
      YOUTH_READ2: ${{ secrets.YOUTH_READ7 }}
      YOUTH_READ3: ${{ secrets.YOUTH_READ8 }}
      YOUTH_READ4: ${{ secrets.YOUTH_READ9 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ10 }}   
      TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点自动阅读六】'
        if: env.YOUTH_READ6
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ6 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME6 }}

      - name: '运行 【中青看点自动阅读七】'
        if: env.YOUTH_READ7
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ7 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME7 }}
          
      - name: '运行 【中青看点自动阅读八】'
        if: env.YOUTH_READ8
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ8 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME8 }}
          
      - name: '运行 【中青看点自动阅读九】'
        if: env.YOUTH_READ9
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ9 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME9 }}
          
      - name: '运行 【中青看点自动阅读十】'
        if: env.YOUTH_READ10                                      
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ10 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME10 }}
          
